---

##
##  ----------------------------------------------------------------
## Copyright 2017 Cisco Systems
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##    http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ------------------------------------------------------------------
##
## Author:  Fabrizio Maccioni, fabrimac@cisco.com
##
## This software is for demonstration purposes only and is not supported
## by Cisco systems.
##
## This Playbook allows to build and apply CLI config to setup gRPC dial-out
## subscriptions in a Cisco device running IOS XE version 16.10.1 or later.
##
## Subscriptions are defined in group_vars/grpc.yaml and the CLI configuration
## is built using a Jinja2 template defined in
## templates/grpc_dial_out_cli.j2
##

- name: Configure gRPC dial-out subscriptions by CLI using Jinja2 templates
  hosts: grpc
  gather_facts: no

  tasks:
    - template:
        src=templates/grpc_dial_out_cli.j2
        dest=configs/grpc_dial_out_cli-{{ inventory_hostname }}.cfg

    - name: Configure periodic subscriptons
      ios_config:
        src: configs/grpc_dial_out_cli-{{ inventory_hostname }}.cfg
