---

##
##  ----------------------------------------------------------------
## Copyright 2017 Cisco Systems
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##    http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ------------------------------------------------------------------
##
## Author:  Fabrizio Maccioni, fabrimac@cisco.com
##
## This software is for demonstration purposes only and is not supported
## by Cisco systems.
##

- name: reset all subscriptions configured by Ansible
  hosts: grpc
  gather_facts: False

  tasks:
    - name: delete periodic subscriptions
      ios_config:
        lines:
            - no telemetry ietf subscription 300
            - no telemetry ietf subscription 301
            - no telemetry ietf subscription 302
            - no telemetry ietf subscription 303
            - no telemetry ietf subscription 304
            - no telemetry ietf subscription 333
