---

##
##  ----------------------------------------------------------------
## Copyright 2017 Cisco Systems
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##    http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ------------------------------------------------------------------
##
## Author:  Fabrizio Maccioni, fabrimac@cisco.com
##
## This software is for demonstration purposes only and is not supported
## by Cisco systems.
##

# ios_fact module Collects a base set of device facts from a remote device running IOS
# NOTE: Possible values for gather_subset argument include all, hardware, config, and interfaces
#
# run the playbook with the -v option to see the collected facts:
#   ansible-playbook -v ios_facts.yaml

- name: test Ansible ios_facts module on Cisco IOS XE
  hosts: ios-xe
  connection: local
  gather_facts: no

  tasks:
    - name: collect hardware facts
      ios_facts:
        gather_subset: hardware

    - name: collect interfaces facts
      ios_facts:
        gather_subset: interfaces
