---

- name: config replace
  hosts: 172.26.249.159
  gather_facts: no

  tasks:
    - name: show module and ip interfaces brief
      ios_command:
        commands:
          - command: 'clear counters GigabitEthernet 0/0'
            prompt: 'Clear "show interface" counters on this interface [confirm]'
            answer: c
