---

- name: test Ansible variables
  hosts: ios-xe

  tasks:
    - name: loop over a list
      with_items: "{{ int_list }}"
      ios_command:
        commands:
          - show run interface {{ item }}
      register: output

    - name: save output to ansible.log file
      debug: msg="{{ output }}"
