---
- name: Remove all configuration files create by the template
  hosts: all
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml

  tasks:
    - file: path=configs/{{ inventory_hostname }}.cfg state=absent

- name: cleanup all the configuration
  hosts: n9k1-fabri
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml

  vars:
    enabled_features:
      - lacp
      - ospf
      - vpc
      - bgp
      - nxapi
      - pim
      - interface-vlan

  tasks:
    - name: 1-VLAN Cleanup - add VLAN 60
      nxos_vlan:
        vlan_id: 60
        name: old
        state: present
        host: "{{ inventory_hostname }}"
        username: "{{username}}"
        transport: "{{ transport }}"
